### ISSUE TITLE
Cannot compile 0.14 on ARMv7: undefined reference to CryptonightR_instruction

### ISSUE THREAD

**Issue by gavriilos** [monero-project/monero#5200]
I am trying to build the [`v0.14.0.0` tag](https://github.com/monero-project/monero/releases/tag/v0.14.0.0) with `-DBUILD_SHARED_LIBS=1` on an ARMv7. At first, compilation failed due to #5178 which I could fix after applying #5184. Now compilation is failing at a later step, when linking the executables:

```
[ 84%] Linking CXX executable ../../bin/monero-wallet-rpc
../crypto/libcncrypto.so: undefined reference to `CryptonightR_instruction87'
../crypto/libcncrypto.so: undefined reference to `CryptonightR_instruction_mov47'
../crypto/libcncrypto.so: undefined reference to `CryptonightR_instruction_mov84'
../crypto/libcncrypto.so: undefined reference to `CryptonightR_instruction237'
../crypto/libcncrypto.so: undefined reference to `CryptonightR_instruction151'
../crypto/libcncrypto.so: undefined reference to `CryptonightR_instruction196'
[...]
collect2: error: ld returned 1 exit status
src/wallet/CMakeFiles/wallet_rpc_server.dir/build.make:133: recipe for target 'bin/monero-wallet-rpc' failed
make[2]: *** [bin/monero-wallet-rpc] Error 1
CMakeFiles/Makefile2:2254: recipe for target 'src/wallet/CMakeFiles/wallet_rpc_server.dir/all' failed
make[1]: *** [src/wallet/CMakeFiles/wallet_rpc_server.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by moneromooo-monero** [comment]
There is a new patch in 5184 now. Does it fix that new error ?

**Comment by gavriilos** [comment]
Thanks for looking into it. It does fix that error but I get a new one:

```
[ 45%] Building C object src/crypto/CMakeFiles/obj_cncrypto.dir/CryptonightR_JIT.c.o
/home/minerador/monero/src/crypto/CryptonightR_JIT.c: In function ‘v4_generate_JIT_code’:
/home/minerador/monero/src/crypto/CryptonightR_JIT.c:83:42: error: ‘instructions_mov’ undeclared (first use in this function)
     const uint8_t* p1 = (const uint8_t*) instructions_mov[c];
                                          ^~~~~~~~~~~~~~~~
/home/minerador/monero/src/crypto/CryptonightR_JIT.c:83:42: note: each undeclared identifier is reported only once for each function it appears in
/home/minerador/monero/src/crypto/CryptonightR_JIT.c:93:40: error: ‘instructions’ undeclared (first use in this function)
   const uint8_t* p1 = (const uint8_t*) instructions[c];
                                        ^~~~~~~~~~~~
src/crypto/CMakeFiles/obj_cncrypto.dir/build.make:494: recipe for target 'src/crypto/CMakeFiles/obj_cncrypto.dir/CryptonightR_JIT.c.o' failed
make[2]: *** [src/crypto/CMakeFiles/obj_cncrypto.dir/CryptonightR_JIT.c.o] Error 1
CMakeFiles/Makefile2:753: recipe for target 'src/crypto/CMakeFiles/obj_cncrypto.dir/all' failed
make[1]: *** [src/crypto/CMakeFiles/obj_cncrypto.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by moneromooo-monero** [comment]
And now ?

**Comment by gavriilos** [comment]
(Sorry for the delay, it takes a long time to compile this on an ARMv7.)
That seems to have fixed it. It compiled successfully and I am now running `monerod`. It is now migrating the blockchain DB version. I'll let you know if something breaks latter on.

**Comment by gavriilos** [comment]
All seems fine. The DB migration was successful, the node got up to speed with the network, and is now correctly handling `monero-wallet-cli` connections.
You can/should merge this into `v0.14`.

**Comment by moneromooo-monero** [comment]
Thanks. It will be.

**Comment by moneromooo-monero** [comment]
+resolved
