### ISSUE TITLE
release-v0.12 error: 'conceal_derivation' overrides a member function

### ISSUE THREAD

**Issue by m2049r** [monero-project/monero#3632]
```C
-- Build files have been written to: /opt/android/monero/build/release.arm
Scanning dependencies of target obj_device
[  0%] Building CXX object src/device/CMakeFiles/obj_device.dir/device.cpp.o
In file included from /opt/android/monero/src/device/device.cpp:31:
/opt/android/monero/src/device/device_default.hpp:96:19: error: 'conceal_derivation' overrides a member function
      but is not marked 'override' [-Werror,-Winconsistent-missing-override]
            bool  conceal_derivation(crypto::key_derivation &derivation, const crypto::public_key &tx_pub...
                  ^
/opt/android/monero/src/device/device.hpp:148:23: note: overridden virtual function is here
        virtual bool  conceal_derivation(crypto::key_derivation &derivation, const crypto::public_key &tx...
                      ^
1 error generated.
```

**Comment by m2049r** [comment]
introduced in commit d481410

**Comment by vtnerd** [comment]
Its a warning flag that can be disabled. Its enabled by `-Wall`. Its triggering because as the name suggests, `override` is used in other places in the class, but not in all possible places. I suggested adding the `override` keyword in the review because the design had base implementations for every virtual method. If the signature changes in one of the functions, the code will still compile but the derived implementation will never be called (because its declaring a new virtual method in the derived class). Arguably, its better to never have a default implementation for a virtual function (like classes in wallet2_api.h), which would've been my preferred proposal if I had done the review earlier. In fact, I think I did propose that, but it was probably too much of an edit for the author at the time.

**Comment by vtnerd** [comment]
Correction: It looks like the base class is all pure virtual method, so the override keyword provides less utility here. I would still recommend it (I usually mark  everything as `override final` where possible), but the situation isn't as bad as I described. Did @m2049r change this, or was I mistaken about the original PR?

**Comment by moneromooo-monero** [comment]
OK, if it only moans when override is partly used, then it's fine. I'll PR that change then, thanks.
