### PR TITLE
Fix build on FreeBSD (release-v0.13)

### PR DESCRIPTION
**Pull request by ndorf**
`CryptonightR_template.S` is being omitted on FreeBSD, resulting in many linker errors along the lines of 
``    ../../src/crypto/libcncrypto.a(CryptonightR_JIT.c.o):(.data+0x3d8): undefined reference to `CryptonightR_instruction123'``

This seems to fix that.

### CODE REVIEW

**Comment by ndorf** [comment]
Done, #5339

**Comment by moneromooo-monero** [comment]
+duplicate
