### PR TITLE
rpc: fix linking error of 6097472, get_output_distribution

### PR DESCRIPTION
**Pull request by ph4r05**
@fluffypony, build of 7e2483e yields the following error

```
Undefined symbols for architecture x86_64:
  "cryptonote::core::get_output_distribution(unsigned long long, unsigned long long, unsigned long long, unsigned long long&, std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >&, unsigned long long&) const", referenced from:
      cryptonote::rpc::RpcHandler::get_output_distribution(cryptonote::core&, unsigned long long, unsigned long long, unsigned long long, bool) in rpc_handler.cpp.o
```

This PR fixes the compilation error.

### CODE REVIEW

**Comment by iDunk5400** [comment]
Hmm, 7e2483e builds fine here on Ubuntu 16.04 (GCC 5.4.0), Ubuntu 18.04 (GCC 7.3.0) and MSYS2 (GCC 8.2.0), all x86_64 targets.

**Comment by moneromooo-monero** [comment]
Kinda doubt it, this commit just removes a division. You must mean another commit. The patch also fixes what appears to be a link error. Moreover, it rpc_base should not depend on cryptonote_core if possible, this brings all the blockchain stuff, which the wallet should not have. Why does rpc need cryptonote_core now ?

**Comment by moneromooo-monero** [comment]
OK, I see rpc_handler got added. Maybe add it to rpc instead of rpc_base, that should be enough hopefully :)

**Comment by ph4r05** [comment]
yep, whatever works :)

**Comment by ph4r05** [comment]
> Kinda doubt it, this commit just removes a division. You must mean another commit. The patch also fixes what appears to be a link error. Moreover, it rpc_base should not depend on cryptonote_core if possible, this brings all the blockchain stuff, which the wallet should not have. Why does rpc need cryptonote_core now ?

I meant the current master. Dont know which particular commit caused it. The linking error, to be precise.

**Comment by moneromooo-monero** [comment]
I take it the new patch fixes it for you ? If so, can you update the commit message to refer to the right commit please ?

**Comment by ph4r05** [comment]
Correct, with this patch Monero builds correctly on OSX, Cmake 3.8.1, clang-1000.11.45.5
