### PR TITLE
added experimental boost::archive::portable_binary_{i|o}archive

### PR DESCRIPTION
**Pull request by kenshi84**
Alternative to PR #1435

### CODE REVIEW

**Comment by moneromooo-monero** [comment]
I like this one better, it's fairly simple.
I assume this is not yet merged into Boost ? If so, I'm wondering whether there are known bugs/problems with it still, and whether it should be included within a custom namespace to avoid problems when/if this gets merged into Boost later.
Also, are all binary_*archive replaced with this in the current code ?

**Comment by kenshi84** [comment]
@moneromooo-monero 
http://www.boost.org/doc/libs/1_62_0/libs/serialization/doc/todo.html
> ### Portable Binary Archives
> 
> Currently there is a portable binary archive in the examples directory. It is not regularly submitted to the exhaustive boost testing regimen but it is tested occasionally and has been used in production code.
> 
> It's missing the following:
> - Addition of portable floating point types. This is not trivial. In addition to handling floating point types of varying sizes, It requires handling invalid floating point numbers (NaNs) in a portable manner.
> - Integration into the Boost testing regimen similar to the other archive classes.

According to the description, there seems to be no known issues/bugs apart from the handling of floating point types. It seems to have not received the same level of testing as other boost components, though.

> Also, are all binary_*archive replaced with this in the current code ?

No. First of all, wallet2.cpp still uses `binary_iarchive` to support reading of existing unportable cache files. Also there are two files that use `binary_*archive`:
- common/boost_serialization_helper.h
- p2p/net_node.inl

**Comment by moneromooo-monero** [comment]
Sounds good. net_node seems to be the peers file. The other, I don't know. Why were they left out ? I think the peers file could be left as it, but I'm uncertain about the second one.

**Comment by moneromooo-monero** [comment]
Oh, actually: you'll want to bump the version for key images files and output files, please, as this changes their formats, and they're versioned. Top of wallet2.cpp.

**Comment by kenshi84** [comment]
@moneromooo-monero I understood the roles played by common/boost_serialization_helper.h and p2p/net_node.inl (they read from/write to config files poolstate.bin and p2pstate.bin at ~/.bitmonero, respectively), and replaced the unportable serializer with the portable one (the unportable version gets copied as *.unportable).

> you'll want to bump the version for key images files and output files, please

`import_key_images` now also supports the unportable version. The output export/import doesn't seem to have to do with the boost serializer.

**Comment by danrmiller** [comment]
@kenshi84 and anyone else, can you suggest anything regarding errors such as this on ubuntu 16.04 amd64:

`In file included from /home/vagrant/slave/monero-static-ubuntu-amd64/build/src/cryptonote_core/cryptonote_boost_serialization.h:41:0,
                 from /home/vagrant/slave/monero-static-ubuntu-amd64/build/src/cryptonote_core/blockchain.cpp:41:
/home/vagrant/slave/monero-static-ubuntu-amd64/build/external/boost/archive/portable_binary_iarchive.hpp: In instantiation of 'void boost::archive::portable_binary_iarchive::load_override(T&) [with T = std::__cxx11::basic_string<char>]':
/home/vagrant/slave/monero-static-ubuntu-amd64/build/external/boost/archive/portable_binary_iarchive.hpp:266:21:   required from here
/home/vagrant/slave/monero-static-ubuntu-amd64/build/external/boost/archive/portable_binary_iarchive.hpp:158:9: error: no matching function for call to 'boost::archive::portable_binary_iarchive::load_override(std::__cxx11::basic_string<char>&)'
         this->detail_common_iarchive::load_override(t);`

Full build attempt here:
https://build.getmonero.org/builders/monero-static-ubuntu-amd64/builds/499/steps/compile/logs/stdio

**Comment by kenshi84** [comment]
@danrmiller Which boost version are you using? It compiles fine with my Mac using boost 1.62.0.

**Comment by kenshi84** [comment]
Looks like APIs for `archive::detail::interface_iarchive<Archive>::load_override` (and likewise for `save_override`) changed  with the update from 1.58 to 1.59:

http://www.boost.org/doc/libs/1_58_0/boost/archive/detail/interface_iarchive.hpp
http://www.boost.org/doc/libs/1_59_0/boost/archive/detail/interface_iarchive.hpp

@fluffypony Would it be reasonable to require the minimum boost version be 1.59? I could tweak the unofficial portable_binary_iarchive.hpp to support both versions, but it seems a bit inappropriate...
