### PR TITLE
epee: partially revert c56ee140 to fix linking errors

### PR DESCRIPTION
**Pull request by jeffro256**
On Linux Mint 21.3, g++ Ubuntu 11.4.0-1ubuntu1~22.04, I get linking error for an undefined reference to `epee::string_tools::trim_right`. This PR reverts the changes to epee_readline.cpp in commit c56ee140, which turns a `boost::trim_right` callsite into an `epee::string_tools::trim_right` callsite.

### CODE REVIEW

**Comment by jeffro256** [comment]
No clue... the linker is the same version as Ubuntu Jammy: 2.38-4ubuntu2.6

Could just be that my environment happened to expose the error, whereas it happened to work correctly by chance in the CI environments? Perhaps neither CMake variables `GNU_READLINE_FOUND` nor `DEPENDS` is set in CI?

**Comment by iamamyth** [comment]
Not voicing an opinion on this revert, but I will note that the original commit had a slight omission: It replaced the boost string functions with epee in contrib/epee/src/readline_buffer.cpp, which eliminated all boost string functions from the source file, but didn't drop the `<boost/algorithm/string.hpp>` include.

**Comment by selsta** [comment]
@jeffro256 It appears to be related to `debug` build. Please also open against release branch.

**Comment by 0xFFFC0000** [comment]
I happen to prefer this to my own way. Since we are using boost for those string manipulation. Let’s just get rid of `epee` wrapper. 

But why it gives undefined references. About that I am not sure. I have to look at the environment to find out

**Comment by rbrunner7** [comment]
On Debian Bookworm current master without this PR has no error for me for a release build, but produces the mentioned link error for a debug build. With this PR cherry-picked into master both builds work.

**Review by selsta — APPROVED** [review]

**Review by 0xFFFC0000 — APPROVED** [review]

**Comment by selsta** [comment]
@jeffro256 The release branch PR contains a `pool_refresh` test, the master branch version does not. Please make them identical.

**Comment by jeffro256** [comment]
@selsta I think this comment was meant for a different set of PRs than this, yeah?

**Comment by selsta** [comment]
yes, probably wrong tab
