### ISSUE TITLE
Easylogging looks for execinfo on android again

### ISSUE THREAD

**Issue by danrmiller** [monero-project/monero#3058]
@moneromooo-monero I believe this broke from #2940.
https://build.getmonero.org/builders/monero-android-armv7/builds/1213/steps/compile/logs/stdio
```
[ 43%] Building CXX object external/easylogging++/CMakeFiles/easylogging.dir/easylogging++.cc.o
In file included from /home/vagrant/slave/monero-android-armv7/build/external/easylogging++/easylogging++.cc:18:
/home/vagrant/slave/monero-android-armv7/build/external/easylogging++/easylogging++.h:362:13: fatal error: 'execinfo.h' file not found
#   include <execinfo.h>
            ^~~~~~~~~~~~
1 error generated.
```

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/3063 should fix it.

**Comment by moneromooo-monero** [comment]
+resolved
