### ISSUE TITLE
No longer works with OSX 10.11 or earlier

### ISSUE THREAD

**Issue by RetroLemur** [monero-project/monero#3774]
Downloaded the OSX binary and ran on 10.11.

Got this error:
dyld: Symbol not found: _clock_gettime
Referenced from /Users/admin/xmr/./monerod (which was built for Mac OS X 10.12)
Expected in /usr/lib/libSystem.B.dylib

Works OK on OS X 10.12 or later.  Is that really required?

**Comment by moneromooo-monero** [comment]
Probably just needs to link against whatever library has _clock_gettime on your machine. Not quite clear whether the message is saying "it's in /usr/lib/libSystem.B.dylib" or "it's not in /usr/lib/libSystem.B.dylib".
Did a previous monero version work on that 10.11 system ?
If so, what version ?

**Comment by gene-telligent** [comment]
I believe this is due to the OSX binary being built for Mac OSX 10.12, which as mentioned uses a newer version of xcode with different linked system libraries!

Adding the variable [CMAKE_OSX_DEPLOYMENT_TARGET](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html#variable:CMAKE_OSX_DEPLOYMENT_TARGET) to the OSX static builds should resolve this, if we'd like to continue to support (technically) legacy OSes.

**Comment by dEBRUYNE-1** [comment]
@RetroLemur - Try the `monerod` that is included in the GUI binaries:

https://github.com/monero-project/monero-gui/releases/tag/v0.12.0.0

It was built on a 10.11 system, whereas `monerod` for the CLI binaries was built on a 10.12 system.

**Comment by dEBRUYNE-1** [comment]
+resolved
