### PR TITLE
Fix: Missing override to get_type(), clang 6

### PR DESCRIPTION
**Pull request by moneroexamples**
Monero does not compile using clang 6.0.1 on Arch Linux, due to:

```
In file included from /home/mwo/monero/src/device/device.cpp:31:
/home/mwo/monero/src/device/device_default.hpp:64:25: error: 'get_type' overrides a member
      function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
            device_type get_type() const {return device_type::SOFTWARE;};
                        ^
/home/mwo/monero/src/device/device.hpp:120:29: note: overridden virtual function is here
        virtual device_type get_type() const = 0;
```

The PR adds the missing override so that compilation with clang works.

### CODE REVIEW

**Comment by coneiric** [comment]
Hi @moneroexamples, this looks like a duplicate of [this fix](https://github.com/monero-project/monero/pull/4412/files).

**Comment by moneroexamples** [comment]
@coneiric 
Ok, haven't noticed this one. Closing my PR then. Thanks for info.
