### ISSUE TITLE
Fails to build with Boost 1.70 (Beta1)

### ISSUE THREAD

**Issue by jbeich** [monero-project/monero#5304]
Regressed by boostorg/asio@a72fbb0b867f. Also reported in hyle-team/epee#1.
```c++
In file included from src/rpc/daemon_handler.cpp:29:
In file included from src/rpc/daemon_handler.h:36:
In file included from src/p2p/net_node.h:47:
In file included from contrib/epee/include/net/abstract_tcp_server2.h:393:
contrib/epee/include/net/abstract_tcp_server2.inl:102:19: error: no member named 'get_io_service' in
      'boost::asio::ssl::stream<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> >'
                m_timer(socket_.get_io_service()),
                        ~~~~~~~ ^
contrib/epee/include/net/abstract_tcp_server2.inl:1210:64: error: no member named 'get_io_service' in
      'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
    if(std::addressof(get_io_service()) == std::addressof(sock.get_io_service()))
                                                          ~~~~ ^
2 errors generated.
```

**Comment by moneromooo-monero** [comment]
Thanks for the report, fixed in https://github.com/monero-project/monero/pull/5328

**Comment by moneromooo-monero** [comment]
+resolved
