### PR TITLE
Unbreak build against Boost 1.67

### LINKED ISSUE #3663: Does not build with boost 1.67.0
Monero does not build with boost 1.67.0.

---

[ 28%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/connection_basic.cpp.o
In file included from monero/contrib/epee/src/connection_basic.cpp:35:
In file included from monero/contrib/epee/include/net/connection_basic.hpp:63:
monero/contrib/epee/include/syncobj.h:37:10: fatal error: 'boost/thread/v2/thread.hpp' file not
      found
#include <boost/thread/v2/thread.hpp>
         ^
1 error generated.
make[3]: *** [contrib/epee/src/CMakeFiles/epee.dir/connection_basic.cpp.o] Error 1
make[2]: *** [contrib/epee/src/CMakeFiles/epee.dir/all] Error 2
make[1]: *** [all] Error 2

---

$ ls /usr/local/Cellar/boost/1.67.0/include/boost/thread/v2/
shared_mutex.hpp

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by boostorg/thread@fea3e33128aa. Fixes #3663.

`<boost/thread/condition_variable.hpp>` is already used by the project without checking `BOOST_VERSION`:
https://github.com/monero-project/monero/blob/6f6521ad7a9832788e07f7f7d181ba29b010e311/src/common/threadpool.h#L30-L32
https://github.com/monero-project/monero/blob/6f6521ad7a9832788e07f7f7d181ba29b010e311/src/wallet/api/wallet.h#L38-L40

### CODE REVIEW

**Comment by jbeich** [comment]
Reworded commit message

**Comment by ilovezfs** [comment]
@jbeich @fluffypony Yes this works: https://gist.github.com/ilovezfs/129d57906c9e07fe704008de18843892

**Comment by nitronick600** [comment]
I can confirm this fixes the build on OSX for me.

**Comment by skftn** [comment]
Repository monero-gui seems to break with 1.67 - perhaps someone could also look at https://github.com/monero-project/monero-gui/issues/1335

**Comment by moneromooo-monero** [comment]
I PR'd it to the branch in https://github.com/monero-project/monero/pull/3707
