### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [monero-project/monero#4695]
After boostorg/logic@23cd89d4c80f build fails. See [error log](https://ptpb.pw/Y-V9).
```c++
src/cryptonote_basic/miner.cpp:640:25: error: assigning to 'bool' from incompatible type 'boost::logic::tribool'
          on_ac_power = !battery_powered;
                        ^~~~~~~~~~~~~~~~
```

**Comment by moneromooo-monero** [comment]
Does this fix it ?

<pre>
diff --git a/src/cryptonote_basic/miner.cpp b/src/cryptonote_basic/miner.cpp
index d0b03593e..d8ca2dd35 100644
--- a/src/cryptonote_basic/miner.cpp
+++ b/src/cryptonote_basic/miner.cpp
@@ -637,7 +637,7 @@ namespace cryptonote
         boost::tribool battery_powered(on_battery_power());
         if(!indeterminate( battery_powered ))
         {
-          on_ac_power = !battery_powered;
+          on_ac_power = !(bool)battery_powered;
         }
       }
 
</pre>

**Comment by jbeich** [comment]
@moneromooo-monero, yes, it fixes build. `(bool)...`, `bool(...)`, `bool{...}` work. However, `!(bool)...` and `(bool)!...` are **not** the same if `...` evaluates to `boost::indeterminate`.

**Comment by moneromooo-monero** [comment]
That's fine in this case since it's only run if it is not indeterminate.

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/monero/pull/4700

**Comment by moneromooo-monero** [comment]
+resolved

**Comment by Franzferdinan51** [comment]
one would apply this patch where? i have the same issue sorry to reopen
