### ISSUE TITLE
Does not build with boost 1.67.0

### ISSUE THREAD

**Issue by pected70** [monero-project/monero#3663]
Monero does not build with boost 1.67.0.

---

[ 28%] Building CXX object contrib/epee/src/CMakeFiles/epee.dir/connection_basic.cpp.o
In file included from monero/contrib/epee/src/connection_basic.cpp:35:
In file included from monero/contrib/epee/include/net/connection_basic.hpp:63:
monero/contrib/epee/include/syncobj.h:37:10: fatal error: 'boost/thread/v2/thread.hpp' file not
      found
#include <boost/thread/v2/thread.hpp>
         ^
1 error generated.
make[3]: *** [contrib/epee/src/CMakeFiles/epee.dir/connection_basic.cpp.o] Error 1
make[2]: *** [contrib/epee/src/CMakeFiles/epee.dir/all] Error 2
make[1]: *** [all] Error 2

---

$ ls /usr/local/Cellar/boost/1.67.0/include/boost/thread/v2/
shared_mutex.hpp

**Comment by ilovezfs** [comment]
Yup. Here is a full log https://gist.github.com/ilovezfs/c9c30a8fc935f50afef945202915eb01

**Comment by jbeich** [comment]
Does #3667 help? Otherwise, same here:
- [FreeBSD 10.3 amd64](http://package22.nyi.freebsd.org/data/103amd64-default-PR227427/2018-04-17_15h33m37s/logs/errors/monero-cli-0.12.0.0.log)
- [FreeBSD 10.3 i386](http://package23.nyi.freebsd.org/data/103i386-default-PR227427/2018-04-17_05h28m01s/logs/errors/monero-cli-0.12.0.0.log)
- [FreeBSD 11.1 amd64](http://package22.nyi.freebsd.org/data/111amd64-default-PR227427/2018-04-17_05h28m08s/logs/errors/monero-cli-0.12.0.0.log])
- [FreeBSD 11.1 i386](http://package23.nyi.freebsd.org/data/111i386-default-PR227427/2018-04-17_17h22m58s/logs/errors/monero-cli-0.12.0.0.log)

**Comment by ilovezfs** [comment]
@jbeich yes #3667 works https://gist.github.com/ilovezfs/129d57906c9e07fe704008de18843892

**Comment by pected70** [comment]
Why not fix upstream https://github.com/sabelnikov/epee?

**Comment by jbeich** [comment]
https://github.com/sabelnikov/epee is not affected. epee bundled in monero is heavily modified but I don't know where to find commit history before 296ae46ed8f8.
